export const COLORS = {
  light: {
    primary: '#007AFF',
    background: '#FFFFFF',
    card: '#FFFFFF',
    text: '#000000',
    border: '#E5E5EA',
    notification: '#FF3B30',
    secondary: '#F2F2F7',
    success: '#34C759',
    warning: '#FF9500',
    danger: '#FF3B30',
    // Form inputs
    placeholder: '#999999',
    inputBorder: '#E0E0E0',
    inputBackground: '#FFFFFF',
    error: '#FF3B30',
    // Component specific colors
    shadowColor: '#000000',
    deleteButton: '#FF3B30',
    // Gray shades
    lightGray: '#F0F0F0',
    mediumGray: '#F5F5F5',
    darkGray: '#666666',
    placeholderGray: '#999999',
    borderGray: '#E0E0E0',
    backgroundGray: '#F8F8F8',
    disabledGray: '#C7C7CC',
    // Button variants
    primaryButtonBackground: '#007AFF',
    primaryButtonText: '#FFFFFF',
    primaryButtonBorder: '#007AFF',
    primaryButtonBackgroundLight: '#F8F9FF',
    dangerButtonBackground: '#FF3B30',
    dangerButtonText: '#FFFFFF',
    ghostButtonBackground: 'transparent',
    ghostButtonText: '#007AFF',
  },
  dark: {
    primary: '#0A84FF',
    background: '#000000',
    card: '#1C1C1E',
    text: '#FFFFFF',
    border: '#38383A',
    notification: '#FF453A',
    secondary: '#1C1C1E',
    success: '#30D158',
    warning: '#FF9F0A',
    danger: '#FF453A',
    // Form inputs
    placeholder: '#8E8E93',
    inputBorder: '#38383A',
    inputBackground: '#1C1C1E',
    error: '#FF453A',
    // Component specific colors
    shadowColor: '#000000',
    deleteButton: '#FF453A',
    // Gray shades
    lightGray: '#2C2C2E',
    mediumGray: '#1C1C1E',
    darkGray: '#8E8E93',
    placeholderGray: '#8E8E93',
    borderGray: '#38383A',
    backgroundGray: '#1C1C1E',
    disabledGray: '#48484A',
    // Button variants
    primaryButtonBackground: '#0A84FF',
    primaryButtonText: '#FFFFFF',
    primaryButtonBorder: '#0A84FF',
    primaryButtonBackgroundLight: '#1C2A3D',
    dangerButtonBackground: '#FF453A',
    dangerButtonText: '#FFFFFF',
    ghostButtonBackground: 'transparent',
    ghostButtonText: '#0A84FF',
  },
} as const;
